=== perpetuooo/SDSI6/Aula 05/voos.dtd
<!ELEMENT movimento (voo+)>
<!ELEMENT voo (origem, destino, horario, compania, operando)>
<!ATTLIST voo codigo CDATA #REQUIRED>
<!ELEMENT origem (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT horario (#PCDATA)>
<!ELEMENT compania (#PCDATA)>
<!ELEMENT operando (#PCDATA)>

=== perpetuooo/SDSI6/Aula 05/voos.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE movimento SYSTEM "voos.dtd">
<?xml-stylesheet type="text/xsl" href="voos.xsl"?>
<movimento>
    <voo codigo="VG456">
        <origem>CGH</origem>
        <destino>POA</destino>
        <horario>14:35</horario>
        <compania>Varig</compania>
        <operando>T</operando>
    </voo>
    <voo codigo="AZ002">
        <origem>VCP</origem>
        <destino>SSA</destino>
        <horario>18:00</horario>
        <compania>Azul</compania>
        <operando>F</operando>
    </voo>
    <voo codigo="VG455">
        <origem>SDU</origem>
        <destino>SSA</destino>
        <horario>15:00</horario>
        <compania>Varig</compania>
        <operando>T</operando
    </voo>
    <voo codigo="JG013">
        <origem>POA</origem>
        <destino>VCP</destino>
        <horario>12:10</horario>
        <compania>TAM</compania>
        <operando>T</operando>
    </voo>
    <voo codigo="GG123">
        <origem>CGH</origem>
        <destino>FLN</destino>
        <horario>06:00</horario>
        <compania>Gol</compania>
        <operando>F</operando>
    </voo>
    <voo codigo="AZ012">
        <origem>VCP</origem>
        <destino>SDU</destino>
        <horario>14:00</horario>
        <compania>Azul</compania>
        <operando>T</operando>
    </voo>
</movimento>
