=== perpetuooo/SDSI6/Aula 05/Biblioteca/biblioteca.dtd
<!ELEMENT biblioteca (livro+)>
<!ELEMENT livro (titulo, autor, editora, emprestimo)>
<!ATTLIST livro codigo ID #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT editora (#PCDATA)>
<!ELEMENT emprestimo (#PCDATA)>

=== perpetuooo/SDSI6/Aula 05/Biblioteca/biblioteca.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>
  <livro codigo="A12345">
    <titulo>Sistemas Distribuidos</titulo>
    <autor>Tanembaum</autor>
    <editora>Pearson</editora>
    <emprestimo>S</emprestimo>
  </livro>
  <livro codigo="A12345">
    <titulo>Programando em C#</titulo>
    <autor>Deitel</autor>
    <editora></editora>
    <emprestimo>N</emprestimo>
  </livro>
</biblioteca>
